sub main()
    _brs_.process.setManifest("/test/e2e/resources/conditional-compilation")
    appInfo = createObject("roAppInfo")

    print appInfo.getID()
    print appInfo.isDev()
    print appInfo.getVersion()
    print appInfo.getTitle()
    print appInfo.getSubtitle()
    print appInfo.getDevID()
    print appInfo.getValue("some_field")

    _brs_.process.setManifest("/test/e2e/non-existing-root")
    print appInfo.getID()
    print appInfo.isDev()
    print appInfo.getVersion()
    print appInfo.getTitle()
    print appInfo.getSubtitle()
    print appInfo.getDevID()
    print appInfo.getValue("some_field")
end sub
