sub main()
    dateTime = createObject("roDateTime")
    dateTime.fromISO8601String("2019-05-02T12:00:00.000")

    print "To ISO string: " dateTime.toISOString()
    print "As a date string long date: " dateTime.asDateString("long-date")
    print "As a date string no week day: " dateTime.asDateString("no-weekday")
    print "As a date string no param: " dateTime.asDateStringNoParam()
    print "Week day: " dateTime.getWeekday()
    print "Full year: " dateTime.getYear()
    print "Month: " dateTime.getMonth()
    print "Day of month: " dateTime.getDayOfMonth()
    print "Hours: " dateTime.getHours()
    print "Minutes: " dateTime.getMinutes()
    print "Seconds: " dateTime.getSeconds()
    print "Milliseconds: " dateTime.getMilliseconds()
    print "Last day of month: " dateTime.getLastDayOfMonth()
    print "Day of week: " dateTime.getDayOfWeek()
end sub