sub Main()
    date = CreateObject("roDateTime")
    date.fromISO8601String("2010-11-12T13:14:15.160")
    print "Full Date: " date.AsDateStringNoParam()
    print "No Week Day: " date.AsDateString("no-weekday")
    print "Short Date: " date.AsDateString("short-date")
    print "Weekday: " date.getWeekday()
    print "Day of Week: " date.getDayOfWeek()
    print "Day of Month: " date.getDayOfMonth()
    print "Month: " date.getMonth()
    print "Year: " date.getYear()
    print "Hours: " date.getHours()
    print "Minutes: " date.getMinutes()
    print "Seconds: " date.getSeconds()
    print "Last Day of Month: " date.getLastDayOfMonth()
    print "Milliseconds: " date.getMilliseconds()
    print "Timezone Offset: " date.getTimeZoneOffset()
    print "ISO String UTC: " date.toISOString()
end sub
